### ISSUE TITLE
Consider implications of Go pointers crossing into C code

### ISSUE THREAD

**Issue by errcw** [go-gl/glow#11]
Per [Go Issue #8310](https://code.google.com/p/go/issues/detail?id=8310) we may be prevented from having Go pointers cross the C boundary. Allowing Go pointers to be used by the OpenGL C functions is core functionality for Glow so we should track the progress of this issue and prepare for whatever implementation Go builds.

**Comment by shurcooL** [comment]
I think all immediate issues have been resolved.

We're on Go 1.6 now, and we've done https://github.com/go-gl/gl/pull/44 to stay up to date with latest Cgo rules.

I don't think there's anything actionable left to do at this time, so I'll close this (re-open otherwise). I think as there are new concrete developments and we need to do something specific, new issues can be opened and acted on.
